act: gelu
batchSize: 2
block_params: '1_1'
conv_type: ['convnext', 'pshuffel']
dec_strds: [2, 2, 2, 2, 2, 2]  #[5, 3, 2, 2, 2]
device: 3
distributed: false
embed: 'pe_1.25_80'
enc_dim: '64_16'
enc_strds: []  # []
encoder_file: ''
epochs: 50000
eval_fps: false
eval_freq: 10
fc_hw: '8_8'
ks: '0_3_3'
loss: L2
lower_width: 12 # 32
lr: 0.001
lr_type: cosine_0.1_1_0.1
manualSeed: 1
modelsize: 6  # 4.5 # 1.5
norm: none
not_resume: false
num_blks: '1_1'
out_bias: tanh
overwrite: false
print_freq: 50
quant_axis: 0
quant_embed_bit: 6
quant_model_bit: 6 # 8
reduce: 2
resize_list: '-1'
saturate_stages: -1
start_epoch: -1
weight: None
workers: 4